version: '3.5'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./files/input:/input:ro
      - ./files/output:/output
    command: parsedmarc -c /parsedmarc.ini /input/*
    depends_on:
      - elasticsearch
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./files/kibana:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.wmr-cdn.com

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  # grafana:
  #   build: ./grafana/
  #   ports:
  #     - 3000:3000
  #   user: root
  #   environment:
  #     GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
  #     GF_AUTH_ANONYMOUS_ENABLED: 'true'