version: '3.5'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./files/input:/input:ro
      - ./files/output:/output
      - /etc/GeoIP.conf:/etc/GeoIP.conf
      - /usr/share/GeoIP:/usr/share/GeoIP
    command: wait-for-it --service elasticsearch:9200 -- parsedmarc -c /parsedmarc.ini /input/*
    depends_on:
      - elasticsearch
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana.wmr-cdn.com
      ELASTIC_PASSWORD: elastic_pass
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - discovery.type=single-node
      - "ELASTIC_PASSWORD=elastic_pass"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_START_PERIOD=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  kibana_data:
    external: true
  elastic_data:
    external: true
