version: '3.5'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./files/input:/input:ro
      - ./files/output:/output
    command: wait-for-it --service elasticsearch:9200 -- parsedmarc -c /parsedmarc.ini /input/*
    depends_on:
      - elasticsearch
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana.wmr-cdn.com

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

volumes:
  kibana_data:
    external: true