version: '3.5'
services:
  # parsedmarc:
  #   build: ./parsedmarc/
  #   volumes:
  #     - ./files/input:/input:ro
  #     - ./files/output:/output
  #     - /etc/GeoIP.conf:/etc/GeoIP.conf
  #     - /usr/share/GeoIP:/usr/share/GeoIP
  #   command: wait-for-it --service elasticsearch:9200 -- parsedmarc -c /parsedmarc.ini /input/*
  #   depends_on:
  #     - elasticsearch
  #   restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana.wmr-cdn.com
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - /mnt/backup/dmarc:/backup
      - /mnt/backup/dmarc-migration:/migration
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - discovery.type=single-node
    restart: always

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_START_PERIOD=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  kibana_data:
    external: true
  elastic_data:
    external: true
